---
functional:
  - Пользователь должен видеть главную страницу и кнопкой для создания игры
  - На странице должен отображаться список доступных языков программирования для выбора
  - Пользователь должен иметь возможность попробовать пробную игру без регистрации
  - Необходимо обеспечить возможность пользователю создать свой профиль или войти в существующий
  - Пользователь должен иметь возможность участвовать в игре против бота
  - Пользователь должен иметь возможность сразиться с друзьями по ссылке
  - Пользователь должен иметь возможность сразиться с другими пользователями
  - Пользователь должен иметь возможность при создании игры выбрать задачу из выпадающего списка
  - Пользователь должен иметь возможность при создании игры выбрать задачу случайную из всего списка
  - Пользователь должен иметь возможность при создании игры выбрать определенное время для решения задачи
  - Представить двум игрокам соревноваться друг с другом в решении задач и видеть написание кода друг у друга
  - Обеспечить таймер в процессе соревнования
  - По истечении времени в процессе соревнования должен быть логический исход (победа, поражение, ничья)
  - Обеспечить подсчет времени, затраченного на решение задачи, для сравнения с другими игроками
  - Сайт должен поддерживать проведение турниров
  - Пользователь должен иметь возможность создавать свои собственные турниры и приглашать других участников
  - Пользователь должен иметь возможность просматривать историю своих игр
  - Пользователь должен видеть свою текущую статистику, включая количество игр, побед
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть мультиязычным (Русский, English)
implicit:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен загружаться быстро, обеспечивая пользователям возможность мгновенно начать игру без задержек
  - Сайту требуется высокая степень доступности, например, система должна обеспечивать время безотказной работы не менее 99,5%, минимизируя количество сбоев и ошибок во время игр
  - Сайт должен быть совместим с последними версиями браузеров
